### ISSUE TITLE
CNCF Sandbox as part of youki

### ISSUE THREAD

**Issue by utam0k** [youki-dev/oci-spec-rs#240]
ref: https://github.com/cncf/sandbox/issues/103#issuecomment-2402006816

**Comment by saschagrunert** [comment]
+1 let’s get this project in shape for that.

**Comment by cgwalters** [comment]
I'm not opposed to this, but this crate is also used in multiple places outside of youki too. I wonder about a direct proposal for addition to e.g. https://github.com/opencontainers/ ?

But in the short term, fine by me!

**Comment by utam0k** [comment]
Thanks for your comments.

>  I wonder about a direct proposal for addition to e.g. https://github.com/opencontainers/ ?

My proposal for OCI runtime spec was rejected before 😭 However, now would be a good time to re-apply to them. Both, OCI and CNCF are fine for me.

**Comment by saschagrunert** [comment]
> My proposal for OCI runtime spec was rejected before

Do you have a reference to that? 

So are we happy to move forward with the CNCF?

**Comment by utam0k** [comment]
Apparently it needs to be moved to an independent org.
https://github.com/containers/youki/issues/2962

**Comment by saschagrunert** [comment]
> Apparently it needs to be moved to an independent org. [containers/youki#2962](https://github.com/containers/youki/issues/2962)

Alright, which one would you prefer or suggest?

**Comment by utam0k** [comment]
I prefer youki-dev in CNCF project. WDYT?

**Comment by saschagrunert** [comment]
@utam0k sounds good!

**Comment by utam0k** [comment]
The transition will take place this Saturday and Sunday in Japan. Please let me know if you have any opinions before then.

**Comment by utam0k** [comment]
> The transition to `youki-dev` will take place this Saturday and Sunday in Japan. Please let me know if you have any opinions before then.

Done. Organized around permissions. This is because we started using teams. Don't be surprised if you are not surprised.

**Comment by utam0k** [comment]
I'll publish it in the org announcement.
